words = [
    "autoincrement",
    "autoreply",
    "autoresponder",
    "autoresponderaction",
    "autoresponderfilter",
    "cooldown",
    "emojicache",
    "grr",
    "leaderboard",
    "medion",
    "mysteriousbot",
    "mysteriouspants",
    "pingsock",
    "replymessage",
    "skorpion",
    "swedishfish",
    "twemoji",
    "twemojis",
]
